name: Check code
run-name: Checking code in ${{ github.head_ref }} PR

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  detect-changes:
    uses: ./.github/workflows/detect-changes.yaml
    with:
      base: ${{ github.base_ref }}

  echo-changes:
    needs: detect-changes
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Output detected changes
        run: echo "Detected changes ${{ needs.detect-changes.outputs.changed-files }}"
    
    
  lint:
    needs: detect-changes
    name: Linting code
    if: needs.detect-changes.outputs.changed-files
    timeout-minutes: 10
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4

      - name: Install lint tool
        run: npm i eslint@8

      - name: Linting changed files
        run: npm i eslint@8
