name: Deploy

on:
  push:
    branches:
      - main
      - dev

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  TARGET_ENV: ${{ github.ref_name == 'main' && 'production' || 'staging' }}

concurrency:
  group: deploy-${{ env.TARGET_ENV }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: ${{ env.TARGET_ENV }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log envs
        run: echo "region - ${{ env.AWS_REGION }}, target_env=${{ env.TARGET_ENV }}"

      - name: Log vars
        run: echo "region - ${{ vars.AWS_REGION }}"

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Sts GetCallerIndentity
        run: |
          aws sts get-caller-identity
