name: Deploy

on:
  push:
    branches:
      - main
      - dev

env:
  AWS_REGION: ${{ vars.AWS_REGION }}

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      target_env: ${{ steps.define-env.outputs.env_name }}
    steps:
      - id: define-env
        run: |
          case ${{ github.ref_name }} in
            main)
              echo "env_name=production" >> "$GITHUB_OUTPUT"    
              ;;
            dev)
              echo "env_name=staging" >> "$GITHUB_OUTPUT"    
              ;;
          esac


  deploy:
    runs-on: ubuntu-latest

    needs: prepare
    if: needs.prepare.outputs.target_env

    environment: ${{ needs.prepare.outputs.target_env }}
    concurrency:
      group: deploy-${{ needs.prepare.outputs.target_env }}
      cancel-in-progress: true
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log envs
        run: echo "region - ${{ env.AWS_REGION }}, target_env=${{ env.TARGET_ENV }}"

      - name: Log vars
        run: echo "region - ${{ vars.AWS_REGION }}"

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Sts GetCallerIndentity
        run: |
          aws sts get-caller-identity
