name: Deploy

on:
  push:
    branches:
      - main
      - dev

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  ECS_SERVICE: ${{ vars.ECS_SERVICE }}
  ECS_CLUSTER: ${{ vars.ECS_CLUSTER }}

jobs:
  prepare:
    name: Preparing...
    runs-on: ubuntu-latest
    outputs:
      target_env: ${{ steps.define-env.outputs.env_name }}
    steps:
      - id: define-env
        run: |
          case ${{ github.ref_name }} in
            main)
              echo "env_name=production" >> "$GITHUB_OUTPUT"    
              ;;
            dev)
              echo "env_name=staging" >> "$GITHUB_OUTPUT"    
              ;;
          esac


  deploy:
    needs: prepare
    if: needs.prepare.outputs.target_env

    name: Deploying
    runs-on: ubuntu-latest

    environment: ${{ needs.prepare.outputs.target_env }}
    concurrency:
      group: deploy-${{ needs.prepare.outputs.target_env }}
      cancel-in-progress: true
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Sts GetCallerIndentity
        run: |
          aws sts get-caller-identity

      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG .
          docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG
          echo "IMAGE=$ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG" >> $GITHUB_OUTPUT

      # Keep a baseline task definition in the repo and render it with the new image
      - name: Render Amazon ECS task definition
        id: taskdef
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: infra/ecs/taskdef.json
          container-name: ${{ vars.CONTAINER_NAME }}
          image: ${{ steps.build-image.outputs.IMAGE }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.taskdef.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true