name: Detect code changes

on:
  workflow_call:
    inputs:
      base:
        required: true
        type: string
      head:
        required: false
        type: string
        default: 'HEAD'
    outputs:
      changed-files:
        description: 'Changed files based on diff between base and HEAD'
        value: ${{ jobs.detect-changes.outputs.changed-files }}

permissions:
  contents: read

jobs:
  detect-changes:
    name: Detecting changes
    runs-on: ubuntu-24.04-arm
    outputs:
      changed-files: ${{ steps.changes-detecting-step.outputs.CHANGED_FILES }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: changes-detecting-step
        name: Detecting changes between ${{ inputs.base }} and ${{ inputs.head }}
        run: echo "CHANGED_FILES=$(git diff --name-only origin/${{ inputs.base }}...${{ inputs.head }} | grep -E '.*\.[tj]sx?$')" >> $GITHUB_OUTPUT

      - run: echo "${{ steps.changes-detecting-step.outputs.CHANGED_FILES }}"
      - run: git diff --name-only origin/${{ inputs.base }}...${{ inputs.head }}
